export const countries = {
  AF: { EN: 'Afghanistan', AR: 'أفغانستان' },
  AL: { EN: 'Albania', AR: 'ألبانيا' },
  DZ: { EN: 'Algeria', AR: 'الجزائر' },
  AD: { EN: 'Andorra', AR: 'أندورا' },
  AO: { EN: 'Angola', AR: 'أنغولا' },
  AG: { EN: 'Antigua and Barbuda', AR: 'أنتيغوا وباربودا' },
  AR: { EN: 'Argentina', AR: 'الأرجنتين' },
  AM: { EN: 'Armenia', AR: 'أرمينيا' },
  AU: { EN: 'Australia', AR: 'أستراليا' },
  AT: { EN: 'Austria', AR: 'النمسا' },
  AZ: { EN: 'Azerbaijan', AR: 'أذربيجان' },
  BS: { EN: 'Bahamas', AR: 'باهاماس' },
  BH: { EN: 'Bahrain', AR: 'البحرين' },
  BD: { EN: 'Bangladesh', AR: 'بنغلاديش' },
  BB: { EN: 'Barbados', AR: 'باربادوس' },
  BY: { EN: 'Belarus', AR: 'بيلاروس' },
  BE: { EN: 'Belgium', AR: 'بلجيكا' },
  BZ: { EN: 'Belize', AR: 'بليز' },
  BJ: { EN: 'Benin', AR: 'بنين' },
  BT: { EN: 'Bhutan', AR: 'بوتان' },
  BO: { EN: 'Bolivia (Plurinational State of)', AR: 'بوليفيا' },
  BA: { EN: 'Bosnia and Herzegovina', AR: 'البوسنة والهرسك' },
  BW: { EN: 'Botswana', AR: 'بوتسوانا' },
  BR: { EN: 'Brazil', AR: 'البرازيل' },
  BN: { EN: 'Brunei Darussalam', AR: 'بروناي' },
  BG: { EN: 'Bulgaria', AR: 'بلغاريا' },
  BF: { EN: 'Burkina Faso', AR: 'بوركينا فاسو' },
  BI: { EN: 'Burundi', AR: 'بوروندي' },
  KH: { EN: 'Cambodia', AR: 'كمبوديا' },
  CM: { EN: 'Cameroon', AR: 'الكاميرون' },
  CA: { EN: 'Canada', AR: 'كندا' },
  CV: { EN: 'Cabo Verde', AR: 'الرأس الأخضر' },
  CF: { EN: 'Central African Republic', AR: 'جمهورية أفريقيا الوسطى' },
  TD: { EN: 'Chad', AR: 'تشاد' },
  CL: { EN: 'Chile', AR: 'تشيلي' },
  CN: { EN: 'China', AR: 'الصين' },
  CO: { EN: 'Colombia', AR: 'كولومبيا' },
  KM: { EN: 'Comoros', AR: 'جزر القمر' },
  CG: { EN: 'Congo', AR: 'جمهورية الكونغو' },
  CD: { EN: 'Congo, Democratic Republic of the', AR: 'جمهورية الكونغو الديمقراطية' },
  CR: { EN: 'Costa Rica', AR: 'كوستاريكا' },
  CI: { EN: "Côte d'Ivoire", AR: 'ساحل العاج' },
  HR: { EN: 'Croatia', AR: 'كرواتيا' },
  CU: { EN: 'Cuba', AR: 'كوبا' },
  CY: { EN: 'Cyprus', AR: 'قبرص' },
  CZ: { EN: 'Czechia', AR: 'جمهورية التشيك' },
  DK: { EN: 'Denmark', AR: 'الدنمارك' },
  DJ: { EN: 'Djibouti', AR: 'جيبوتي' },
  DM: { EN: 'Dominica', AR: 'دومينيكا' },
  DO: { EN: 'Dominican Republic', AR: 'جمهورية الدومينيكان' },
  EC: { EN: 'Ecuador', AR: 'الإكوادور' },
  EG: { EN: 'Egypt', AR: 'مصر' },
  SV: { EN: 'El Salvador', AR: 'السلفادور' },
  GQ: { EN: 'Equatorial Guinea', AR: 'غينيا الاستوائية' },
  ER: { EN: 'Eritrea', AR: 'إريتريا' },
  EE: { EN: 'Estonia', AR: 'إستونيا' },
  ET: { EN: 'Ethiopia', AR: 'إثيوبيا' },
  FJ: { EN: 'Fiji', AR: 'فيجي' },
  FI: { EN: 'Finland', AR: 'فنلندا' },
  FR: { EN: 'France', AR: 'فرنسا' },
  GA: { EN: 'Gabon', AR: 'الغابون' },
  GM: { EN: 'Gambia', AR: 'غامبيا' },
  GE: { EN: 'Georgia', AR: 'جورجيا' },
  DE: { EN: 'Germany', AR: 'ألمانيا' },
  GH: { EN: 'Ghana', AR: 'غانا' },
  GR: { EN: 'Greece', AR: 'اليونان' },
  GD: { EN: 'Grenada', AR: 'غرينادا' },
  GT: { EN: 'Guatemala', AR: 'غواتيمالا' },
  GN: { EN: 'Guinea', AR: 'غينيا' },
  GW: { EN: 'Guinea-Bissau', AR: 'غينيا بيساو' },
  GY: { EN: 'Guyana', AR: 'غيانا' },
  HT: { EN: 'Haiti', AR: 'هايتي' },
  HN: { EN: 'Honduras', AR: 'هندوراس' },
  HU: { EN: 'Hungary', AR: 'المجر' },
  IS: { EN: 'Iceland', AR: 'آيسلندا' },
  IN: { EN: 'India', AR: 'الهند' },
  ID: { EN: 'Indonesia', AR: 'إندونيسيا' },
  IR: { EN: 'Iran (Islamic Republic of)', AR: 'إيران' },
  IQ: { EN: 'Iraq', AR: 'العراق' },
  IE: { EN: 'Ireland', AR: 'أيرلندا' },
  IL: { EN: 'Israel', AR: 'إسرائيل' },
  IT: { EN: 'Italy', AR: 'إيطاليا' },
  JM: { EN: 'Jamaica', AR: 'جامايكا' },
  JP: { EN: 'Japan', AR: 'اليابان' },
  JO: { EN: 'Jordan', AR: 'الأردن' },
  KZ: { EN: 'Kazakhstan', AR: 'كازاخستان' },
  KE: { EN: 'Kenya', AR: 'كينيا' },
  KI: { EN: 'Kiribati', AR: 'كيريباتي' },
  KP: { EN: "Korea (Democratic People's Republic of)", AR: 'كوريا الشمالية' },
  KR: { EN: 'Korea, Republic of', AR: 'كوريا الجنوبية' },
  KW: { EN: 'Kuwait', AR: 'الكويت' },
  KG: { EN: 'Kyrgyzstan', AR: 'قيرغيزستان' },
  LA: { EN: "Lao People's Democratic Republic", AR: 'لاوس' },
  LV: { EN: 'Latvia', AR: 'لاتفيا' },
  LB: { EN: 'Lebanon', AR: 'لبنان' },
  LS: { EN: 'Lesotho', AR: 'ليسوتو' },
  LR: { EN: 'Liberia', AR: 'ليبيريا' },
  LY: { EN: 'Libya', AR: 'ليبيا' },
  LI: { EN: 'Liechtenstein', AR: 'ليختنشتاين' },
  LT: { EN: 'Lithuania', AR: 'ليتوانيا' },
  LU: { EN: 'Luxembourg', AR: 'لوكسمبورغ' },
  MK: { EN: 'North Macedonia', AR: 'مقدونيا' },
  MG: { EN: 'Madagascar', AR: 'مدغشقر' },
  MW: { EN: 'Malawi', AR: 'مالاوي' },
  MY: { EN: 'Malaysia', AR: 'ماليزيا' },
  MV: { EN: 'Maldives', AR: 'جزر المالديف' },
  ML: { EN: 'Mali', AR: 'مالي' },
  MT: { EN: 'Malta', AR: 'مالطا' },
  MH: { EN: 'Marshall Islands', AR: 'جزر مارشال' },
  MR: { EN: 'Mauritania', AR: 'موريتانيا' },
  MU: { EN: 'Mauritius', AR: 'موريشيوس' },
  MX: { EN: 'Mexico', AR: 'المكسيك' },
  FM: { EN: 'Micronesia (Federated States of)', AR: 'ولايات ميكرونيسيا المتحدة' },
  MA: { EN: 'Morocco', AR: 'المغرب' },
  MD: { EN: 'Moldova, Republic of', AR: 'مولدوفا' },
  MC: { EN: 'Monaco', AR: 'موناكو' },
  MN: { EN: 'Mongolia', AR: 'منغوليا' },
  ME: { EN: 'Montenegro', AR: 'الجبل الأسود' },
  MZ: { EN: 'Mozambique', AR: 'موزمبيق' },
  MM: { EN: 'Myanmar', AR: 'ميانمار' },
  NA: { EN: 'Namibia', AR: 'ناميبيا' },
  NR: { EN: 'Nauru', AR: 'ناورو' },
  NP: { EN: 'Nepal', AR: 'نيبال' },
  NL: { EN: 'Netherlands', AR: 'هولندا' },
  NZ: { EN: 'New Zealand', AR: 'نيوزيلندا' },
  NI: { EN: 'Nicaragua', AR: 'نيكاراغوا' },
  NE: { EN: 'Niger', AR: 'النيجر' },
  NG: { EN: 'Nigeria', AR: 'نيجيريا' },
  NO: { EN: 'Norway', AR: 'النرويج' },
  OM: { EN: 'Oman', AR: 'عمان' },
  PK: { EN: 'Pakistan', AR: 'باكستان' },
  PW: { EN: 'Palau', AR: 'بالاو' },
  PA: { EN: 'Panama', AR: 'بنما' },
  PG: { EN: 'Papua New Guinea', AR: 'بابوا غينيا الجديدة' },
  PY: { EN: 'Paraguay', AR: 'باراغواي' },
  PE: { EN: 'Peru', AR: 'بيرو' },
  PH: { EN: 'Philippines', AR: 'الفلبين' },
  PL: { EN: 'Poland', AR: 'بولندا' },
  PT: { EN: 'Portugal', AR: 'البرتغال' },
  QA: { EN: 'Qatar', AR: 'قطر' },
  RO: { EN: 'Romania', AR: 'رومانيا' },
  RU: { EN: 'Russian Federation', AR: 'روسيا' },
  RW: { EN: 'Rwanda', AR: 'رواندا' },
  KN: { EN: 'Saint Kitts and Nevis', AR: 'سانت كيتس ونيفيس' },
  LC: { EN: 'Saint Lucia', AR: 'سانت لوسيا' },
  VC: { EN: 'Saint Vincent and the Grenadines', AR: 'سانت فينسنت والغرينادين' },
  WS: { EN: 'Samoa', AR: 'ساموا' },
  SM: { EN: 'San Marino', AR: 'سان مارينو' },
  ST: { EN: 'Sao Tome and Principe', AR: 'ساو تومي وبرينسيب' },
  SA: { EN: 'Saudi Arabia', AR: 'السعودية' },
  SN: { EN: 'Senegal', AR: 'السنغال' },
  RS: { EN: 'Serbia', AR: 'صربيا' },
  SC: { EN: 'Seychelles', AR: 'سيشل' },
  SL: { EN: 'Sierra Leone', AR: 'سيراليون' },
  SG: { EN: 'Singapore', AR: 'سنغافورة' },
  SK: { EN: 'Slovakia', AR: 'سلوفاكيا' },
  SI: { EN: 'Slovenia', AR: 'سلوفينيا' },
  SB: { EN: 'Solomon Islands', AR: 'جزر سليمان' },
  SO: { EN: 'Somalia', AR: 'الصومال' },
  ZA: { EN: 'South Africa', AR: 'جنوب أفريقيا' },
  SS: { EN: 'South Sudan', AR: 'جنوب السودان' },
  ES: { EN: 'Spain', AR: 'إسبانيا' },
  LK: { EN: 'Sri Lanka', AR: 'سريلانكا' },
  SD: { EN: 'Sudan', AR: 'السودان' },
  SR: { EN: 'Suriname', AR: 'سورينام' },
  SZ: { EN: 'Eswatini', AR: 'إسواتيني' },
  SE: { EN: 'Sweden', AR: 'السويد' },
  CH: { EN: 'Switzerland', AR: 'سويسرا' },
  SY: { EN: 'Syrian Arab Republic', AR: 'سوريا' },
  TJ: { EN: 'Tajikistan', AR: 'طاجيكستان' },
  TZ: { EN: 'Tanzania, United Republic of', AR: 'تنزانيا' },
  TH: { EN: 'Thailand', AR: 'تايلاند' },
  TL: { EN: 'Timor-Leste', AR: 'تيمور الشرقية' },
  TG: { EN: 'Togo', AR: 'توغو' },
  TO: { EN: 'Tonga', AR: 'تونغا' },
  TT: { EN: 'Trinidad and Tobago', AR: 'ترينيداد وتوباغو' },
  TN: { EN: 'Tunisia', AR: 'تونس' },
  TR: { EN: 'Turkey', AR: 'تركيا' },
  TM: { EN: 'Turkmenistan', AR: 'تركمانستان' },
  TV: { EN: 'Tuvalu', AR: 'توفالو' },
  UG: { EN: 'Uganda', AR: 'أوغندا' },
  UA: { EN: 'Ukraine', AR: 'أوكرانيا' },
  AE: { EN: 'United Arab Emirates', AR: 'الإمارات العربية المتحدة' },
  GB: { EN: 'United Kingdom of Great Britain and Northern Ireland', AR: 'المملكة المتحدة' },
  US: { EN: 'United States of America', AR: 'الولايات المتحدة' },
  UY: { EN: 'Uruguay', AR: 'الأوروغواي' },
  UZ: { EN: 'Uzbekistan', AR: 'أوزبكستان' },
  VU: { EN: 'Vanuatu', AR: 'فانواتو' },
  VE: { EN: 'Venezuela (Bolivarian Republic of)', AR: 'فنزويلا' },
  VN: { EN: 'Viet Nam', AR: 'فيتنام' },
  YE: { EN: 'Yemen', AR: 'اليمن' },
  ZM: { EN: 'Zambia', AR: 'زامبيا' },
  ZW: { EN: 'Zimbabwe', AR: 'زيمبابوي' },
  AI: { EN: 'Anguilla', AR: 'أنجولا' },
  AQ: { EN: 'Antarctica', AR: 'انتاركتيكا' },
  AS: { EN: 'American Samoa', AR: 'ساموا الأمريكية' },
  AW: { EN: 'Aruba', AR: 'اروبا' }
};
