import { registerEnumType } from '@nestjs/graphql';

export enum MediaRequestReplyEnum {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED'
}
registerEnumType(MediaRequestReplyEnum, {
  name: 'MediaRequestReplyEnum'
});

export enum MediaStatusEnum {
  INITIATED = 'INITIATED',
  VIDEO_COMPLETED = 'VIDEO_COMPLETED',
  VIDEO_JOINED_BY_DOCTOR = 'VIDEO_JOINED_BY_DOCTOR',
  VIDEO_JOINED_BY_PATIENT = 'VIDEO_JOINED_BY_PATIENT',
  VIDEO_CANCELED_BY_PATIENT = 'VIDEO_CANCELED_BY_PATIENT',
  VIDEO_CANCELED_BY_DOCTOR = 'VIDEO_CANCELED_BY_DOCTOR',
  VIDEO_NO_REPLY_FROM_DOCTOR = 'VIDEO_NO_REPLY_FROM_DOCTOR',
  VIDEO_NO_REPLY_FROM_PATIENT = 'VIDEO_NO_REPLY_FROM_PATIENT',
  VOICE_NO_REPLY_FROM_PATIENT = 'VOICE_NO_REPLY_FROM_PATIENT',
  VOICE_NO_REPLY_FROM_DOCTOR = 'VOICE_NO_REPLY_FROM_DOCTOR',
  VOICE_CANCELED_BY_PATIENT = 'VOICE_CANCELED_BY_PATIENT',
  VOICE_CANCELED_BY_DOCTOR = 'VOICE_CANCELED_BY_DOCTOR',
  VOICE_JOINED_BY_DOCTOR = 'VOICE_JOINED_BY_DOCTOR',
  VOICE_JOINED_BY_PATIENT = 'VOICE_JOINED_BY_PATIENT',
  VOICE_COMPLETED = 'VOICE_COMPLETED'
}
registerEnumType(MediaStatusEnum, { name: 'MediaStatusEnum' });

export enum ChangeMediaStatusEnum {
  VIDEO_COMPLETED = 'VIDEO_COMPLETED',
  VIDEO_CANCELED_BY_PATIENT = 'VIDEO_CANCELED_BY_PATIENT',
  VIDEO_CANCELED_BY_DOCTOR = 'VIDEO_CANCELED_BY_DOCTOR',
  VIDEO_NO_REPLY_FROM_DOCTOR = 'VIDEO_NO_REPLY_FROM_DOCTOR',
  VIDEO_NO_REPLY_FROM_PATIENT = 'VIDEO_NO_REPLY_FROM_PATIENT',
  VOICE_NO_REPLY_FROM_PATIENT = 'VOICE_NO_REPLY_FROM_PATIENT',
  VOICE_NO_REPLY_FROM_DOCTOR = 'VOICE_NO_REPLY_FROM_DOCTOR',
  VOICE_CANCELED_BY_PATIENT = 'VOICE_CANCELED_BY_PATIENT',
  VOICE_CANCELED_BY_DOCTOR = 'VOICE_CANCELED_BY_DOCTOR',
  VOICE_COMPLETED = 'VOICE_COMPLETED'
}
registerEnumType(ChangeMediaStatusEnum, { name: 'ChangeMediaStatusEnum' });

export enum AgoraAppointmentStatusEnum {
  IN_PROGRESS = 'IN_PROGRESS'
}
registerEnumType(AgoraAppointmentStatusEnum, { name: 'AgoraAppointmentStatusEnum' });

export enum AgoraMediaTypeEnum {
  VOICE = 'VOICE',
  VIDEO = 'VIDEO'
}
registerEnumType(AgoraMediaTypeEnum, { name: 'AgoraMediaTypeEnum' });
